pragma solidity ^0.4.13;

contract Transporter {

  // id is generated by our KYC
  string public id;
  string public name;

  // kyc processID
  string public processID;

  // Added after each transport
  mapping (string => string) internal performedTransports;
  mapping (string => uint256) internal trustScore;

  function Transportist (string identification, string transportersName) {
    id = identification;
    name = transportersName;
  }
}
