pragma solidity ^0.4.13;

import './Verified.sol';

contract Transporter is Verified{

  // id is generated by our KYC
  string public id;
  string public name;

  mapping (string => string) public performedTransports;

  function Transportist (string identification, string name) {
    id = identification;
    name = name;
  }
}
